### ISSUE TITLE
Suggestion: change format for mobile phone number to be like +47 222 33 222

### ISSUE THREAD

**Issue by stianwestvig** [bouvet/email_signature#2]
I did this, and tried creating a pull request, but have no access :)

**Comment by nemzes** [comment]
You can ask IT Drift to allow you into the "bouvet" organisation; it would be a shame to let a good pull request go to waste. :)

**Comment by gdubya** [comment]
Or fork and push back?

**Comment by nemzes** [comment]
I think the number formatting works best in different ways for different numbers. It's just they way you'd say it… "222 33 222" works better than "22 23 32 22", definitely. But "20 40 30 40" works better than "204 03 040". I'll close this by saying "leave to best judgement".  :)

**Comment by nemzes** [comment]
Added a note about this on the README.
